### ISSUE TITLE
Style ändern (color HEX codes)  (Themes)

### ISSUE THREAD

**Issue by Plenet-OTAKU** [Newcomer1989/TSN-Ranksystem#882]
**3) Was wäre der Vorteil?**

Die Farbe vom Panel ändern (Charts, Buttons, Background, Texte)
 
**Neue Funktion**
 
Hex Codes ändern (vielleicht auch Expotieren das man Thmes erstellen kann und teilen)
 
**2) Wo soll es sich befinden? **

Neuer Bereich in Webinterface Names **Theme** wo man die HEX Codes anpassen kann und vielleicht anderen Spielereien oder so
 
**3) Was wäre der Nutzen?**

Das man die Website besser via _**iframe**_ benutzen kann z.b. wenn man eine "Dark" Theme Website hat.
Oder wenn man die Website so benutzen will das man die Farben einfach auf seinen Geschmack anpassen kann

**Comment by Plenet-OTAKU** [comment]
### **ENG version**


 
**3) What would be the advantage?**

Change the color of the panel (charts, buttons, background, texts)
 
**New function**
 
Change hex codes (maybe also export that you can create thmes and share)
 
**2) Where should it be located? **

New area in Webinterface  as **Theme** where you can customize the HEX Codes and maybe other staff
 
**3) What would be the benefit?**

That you can better  include the website via _**iframe**_ e.g. if you have a "dark" theme website.
Or if you want to use the "standalone" website so that you can easily customize the colors to your taste.

**Comment by Newcomer1989** [comment]
Die Funktion ist Teil der aktuellen Beta, falls du das vorab mal probieren magst
`1.3.22-beta-1`

In die Beta kommst du über das `Webinterface -> Anderes -> Update-Channel`

Genau oberhalb dieses Feldes befindet sich nach dem Update dann auch die Auswahl des Styles - Beschreibung, wie immer, in der online Hilfe (klick auf den Titel).

Das Update erfolgt nach Botneustart dann nach einiger Zeit automatisch. Ansonsten kann man es mit dem Bot Command `!update` beschleunigen.

**Comment by Plenet-OTAKU** [comment]
> 

habe jetzt die `1.3.22-beta-2` und es hat sich nix verändert

**Comment by Plenet-OTAKU** [comment]
> Die Funktion ist Teil der aktuellen Beta, falls du das vorab mal probieren magst `1.3.22-beta-1`
> 
> In die Beta kommst du über das `Webinterface -> Anderes -> Update-Channel`
> 
> Genau oberhalb dieses Feldes befindet sich nach dem Update dann auch die Auswahl des Styles - Beschreibung, wie immer, in der online Hilfe (klick auf den Titel).
> 
> Das Update erfolgt nach Botneustart dann nach einiger Zeit automatisch. Ansonsten kann man es mit dem Bot Command `!update` beschleunigen.
> 
> Gebe gerne mal Feedback, ob es passt oder wenn noch was zu ändern / verbessern wäre.


Wie ändere ich die Farben von den js grafen (donut etc)?

**Comment by Newcomer1989** [comment]
Die Farben werden per JavaScript über die Morris Charts bzw. Donuts bestimmt.
https://morrisjs.github.io/morris.js/

Werde mir das mal ansehen, dass man auch hier die Werte übersteuern kann.
Hatte überlegt generell ein eigenes Javascript mit einbinden zu lassen, falls man da etwas hinzufügen möchte. Vielleicht finde ich auch noch einen Weg die Farben aus einer CSS Klasse an die Morris JS Funktionen zu übergeben.

**Comment by Plenet-OTAKU** [comment]
was eigenes ist eine gute idee

**Comment by Plenet-OTAKU** [comment]
und vielleicht die basic farben einfach nur 1x als hex code nutzen weil es ist schon bisschen nervig wenn man was ändern will das man die 4-6x ändern muss

**Comment by Newcomer1989** [comment]
Für die Donuts und den Servergraphen gibt es die folgenden neuen CSS Einträge, welche die Farbe bestimmen und folglich im eigenen Style übersteuert werden können:

```CSS
#donut_time_color_1{color:#0b62a4}
#donut_time_color_2{color:#3980b5}
#donut_version_color_1{color:#5cb85c}
#donut_version_color_2{color:#73C773}
#donut_version_color_3{color:#8DD68D}
#donut_version_color_4{color:#AAE6AA}
#donut_version_color_5{color:#C9F5C9}
#donut_version_color_6{color:#E6FFE6}
#donut_nation_color_1{color:#f0ad4e}
#donut_nation_color_2{color:#ffc675}
#donut_nation_color_3{color:#fecf8d}
#donut_nation_color_4{color:#ffdfb1}
#donut_nation_color_5{color:#fce8cb}
#donut_nation_color_6{color:#fdf3e5}
#donut_platform_color_1{color:#d9534f}
#donut_platform_color_2{color:#FF4040}
#donut_platform_color_3{color:#FF5050}
#donut_platform_color_4{color:#FF6060}
#donut_platform_color_5{color:#FF7070}
#donut_platform_color_6{color:#FF8080}
#graph_lineColors_1{color:#0b62a4}
#graph_lineColors_2{color:#7a92a3}
#graph_pointFillColors_1{color:#3980b5}
#graph_pointFillColors_2{color:#98aab7}
#graph_pointStrokeColors_1{color:#0b62a4}
#graph_pointStrokeColors_2{color:#7a92a3}
#graph_fillOpacity{opacity:0.4}
.graph_tooltip_client_color{color:#0b62a4}
.graph_tooltip_channel_color{color:#7a92a3}
```
